baseURL = 'https://capeie-dev.github.io/kpweb/'
languageCode = 'en-us'
title = "Krishna Prasad"
theme = 'minimal'

[params]
  author = "Krishna Prasad"
  description = "AI Engineer - Exploring fundamentals, building projects, sharing thoughts"
  
[menu]
  [[menu.main]]
    name = "Fundamentals"
    url = "/fundamentals/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
